apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: 
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: my-app-container
          image: gcr.io/esraa-abdelaziz/my-app:latest
          ports:
          - containerPort: 80
          envFrom:
          - configMapRef:
              name: app-cm
