apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web-app
  template:
    metadata:
      labels:
        name: web-app
    spec:
      containers:
      - name: my-app-container
        image: gcr.io/esraa-abdelaziz/my-app:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config-map

