apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-web
spec:
  selector:
    matchLabels:
      app: redis-web
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-web
    spec:
      containers:
        - name: redis
          image: gcr.io/esraa-abdelaziz/my-app:latest
          ports:
            - containerPort: 80 
      
