apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: python-img
          image: gcr.io/esraa-abdelaziz/my-python-image:latest
          env:
            - name: REDIS_HOST
              value: service-redis
          ports:
            - containerPort: 80
