apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: python-img
          image: gcr.io/esraa-abdelaziz/my-app:latest
          env:
            - name: REDIS_HOST
              value: service-redis
          ports:
            - containerPort: 8000
